### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/DIO_SMA#11]
There are some files included in project file but in the repo.

Class	|Document	|Source|	Message|	Time|	Date|	No.
--------|----------------------|-----------|---------------|---------------|---------|-------
[Warning]	|PANEL_DIO_SMA.brd	|Project	|PANEL_DIO_SMA.brd could not be found and will be removed from the project.	|11:36:09|	30.11.2020	|7
[Warning]	|PANEL_DIO_SMA.DXF	|Project	|PANEL_DIO_SMA.DXF could not be found and will be removed from the project.	|11:36:09|	30.11.2020	|8
[Warning]	|PANEL_DIO_SMA.step	|Project	|PANEL_DIO_SMA.step could not be found and will be removed from the project.	|11:36:09|	30.11.2020	|9
[Warning]	|Pro3FB6.xls	|Project	|Pro3FB6.xls could not be found and will be removed from the project.	|11:36:09	|30.11.2020	|10
[Warning]	|ProB024.xls	|Project	|ProB024.xls could not be found and will be removed from the project.	|11:36:09	|30.11.2020	|11
[Warning]	|ProBE60.xls	|Project	|ProBE60.xls could not be found and will be removed from the project.	|11:36:09	|30.11.2020	|12

**Comment by gkasprow** [comment]
These are the output files, it seems they were added by mistake to the project

**Comment by gkasprow** [comment]
I modified the settings so the output files won't be added to the project
