### ISSUE TITLE
CPCIS Compatibility

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/DIO_SMA#12]
[There was discussion](https://github.com/sinara-hw/DIO_BNC/issues/11) of making this board 160mm long so that there was an isolated DIO module available right away for CPCIS.  Just checking this was decided against and not just forgotten.

**Comment by gkasprow** [comment]
I don't remember what the conclusion was.
We already have 160mm EEM  16-CH DIO_MCX and individually isolated 16-CH DIO MCX in native CPCIS format. Each of them can support 8 channels without mezzanine.

**Comment by dtcallcock** [comment]
> We already have ... individually isolated 16-CH DIO MCX in native CPCIS format

I hadn't spotted [that new repository](https://github.com/sinara-hw/DIO_MCX_Isolated) when I posted this.  Seems like there is little need either way then.
