### ISSUE TITLE
Fast output rise time causes unexpected termination FET turn on

### ISSUE THREAD

**Issue by TopQuark12** [sinara-hw/DIO_SMA#13]
Under guidance from @sbourdeauducq , it was discovered that a combination of fast output rise time and variation in the BSS138L parasitic capacitance and turn-on voltage, may cause an unexpected turn-on on some BSS138L termination FETs during output switching. 

This effect causes a weird slope to appear towards the top of the pulse that lasts for ~1us, and is more pronounced when driving unterminated loads. Even on output channels that do not exhibit this issue, measuring the Vgs of the FETs shows the margin between the output working as expected and the issue showing is very slim. 

In the below screenshots, the yellow trace shows the output connected to scope with 50cm coax and with 1M input termination. Blue trace is the Vgs of the BSS138L FET.

The issue on failed output channels:
![Bad fet 1M](https://user-images.githubusercontent.com/32214395/122527219-b56fe300-d04d-11eb-9cc0-1b7de598302e.png)

Output on "good" channels, but Vgs shows it is marginally working:
![Good fet 1M](https://user-images.githubusercontent.com/32214395/122527440-e18b6400-d04d-11eb-9383-d7f22a7de375.png)

Adding a 1nF cap across gate and source of the FET fixes the issue.
![image-42236a04-afd5-4574-a813-a7ec35c39a57](https://user-images.githubusercontent.com/32214395/122527669-1eeff180-d04e-11eb-8032-7487f86e25dc.jpg)

![After](https://user-images.githubusercontent.com/32214395/122527515-f536ca80-d04d-11eb-95b3-f587c487a5fd.png)

**Comment by hartytp** [comment]
good catch!

**Comment by sbourdeauducq** [comment]
Does it improve the situation on those cards where the effect is not so pronounced, e.g. https://github.com/sinara-hw/DIO_SMA/issues/4#issuecomment-841132777 ?

**Comment by TopQuark12** [comment]
It does!

Before (Vgs not measured, probing it changes the output signal on this channel):
![SDS2504X Plus_PNG_39](https://user-images.githubusercontent.com/32214395/122534875-8d847d80-d055-11eb-99ba-0aec105351fa.png)


After soldering 1nF cap:
![SDS2504X Plus_PNG_40](https://user-images.githubusercontent.com/32214395/122534931-9c6b3000-d055-11eb-9788-e02352f56984.png)

**Comment by gkasprow** [comment]
Does it exist in the boards where the resistor between G and S was installed to eliminate the previous issue related to signal edges (https://github.com/sinara-hw/DIO_SMA/issues/4)?

**Comment by sbourdeauducq** [comment]
Yes. And if you look at the duration of the disturbance it's in the ballpark of the RC product of that resistor with the gate capacitance.
