### ISSUE TITLE
Si8651 is unavailable

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/DIO_SMA#14]
It's basically impossible to get DIO-SMA (and DIO-BNC) in reasonable time because of the Si8651.

Creotech mentioned a redesign of the cards to accept an alternative isolator. What is the latest status?

**Comment by gkasprow** [comment]
It's already in the repo. Large production run was started.

**Comment by sbourdeauducq** [comment]
Could you make a release?

**Comment by gkasprow** [comment]
https://github.com/sinara-hw/DIO_SMA/releases/tag/v1.4
