### ISSUE TITLE
v1.4 resistors changes

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/DIO_SMA#15]
Due to wrong resistive divider, enable of isolators and transceiver direction couldn't be changed. Resistors values are changed to:

<html>
<body>

Des. | Value
-- | --
R195 | 3k9
R194 | 1k
R196 | 510
R38 | 470
R39 | 470
R220 | 3k9
R217 | 1k
R44 | 510
R42 | 470
R43 | 470

</body>
</html>

**Comment by gkasprow** [comment]
These changes are needed only for v1.4. V1.4.1 and v1.4.2 do not need them because the source of the issues was removed.
