### ISSUE TITLE
replace DC/DC and other changes from DIO_BNC

### ISSUE THREAD

**Issue by jordens** [sinara-hw/DIO_SMA#3]
DIO_SMA should see an update and adopt the improvements from DIO_BNC:

* use the beefier Murata DC/DC (and https://github.com/sinara-hw/DIO_BNC/issues/3)
* panel grounding

**Comment by gkasprow** [comment]
I'm afraid these nice Murata modules are no longer produced.

**Comment by gkasprow** [comment]
2W  TMH1205S were used
