### ISSUE TITLE
Potential issue causing obvious rising edges

### ISSUE THREAD

**Issue by ghost** [sinara-hw/DIO_SMA#4]
### Issue description

A user of [ARTIQ](https://github.com/m-labs/artiq) reported an [issue](https://forum.m-labs.hk/d/40-output-of-the-ttlout/7) about an obvious rising edge when the DIO generates 5-ms pulses. I was able to reproduce the same oscilloscope output as him, which is:
![ttl4-500mv](https://user-images.githubusercontent.com/6345728/67929597-a4fcc180-fbf8-11e9-8e49-9cab13f86dad.png)_Fig. 1: TTL4 output on an oscilloscope._

On the other hand, the rising edge of a longer pulse (400 ms) looked like this:
![ttl5-500mv](https://user-images.githubusercontent.com/6345728/67929872-6b788600-fbf9-11e9-8e4c-d830965b1878.png)_Fig. 2: TTL5 output on an oscilloscope._

### Steps to reproduce the issue

1. Copy [this Python script](https://gist.github.com/HarryHo90sHK/8731ff8008e99e76628f8671208e8116) to your local folder.
2. Prepare an ARTIQ system with a TTL output. For my test, an SMA-DIO is connected to a Kasli on EEM port 0. Note that the original poster was [using a BNC-DIO instead](https://forum.m-labs.hk/d/40-output-of-the-ttlout/8), but that also produced a similar shape on the waveform.
3. Use ARTIQ to run the script. Please follow the [official manual](https://m-labs.hk/artiq/manual-beta/index.html) for details.
4. Trace the output waveform of TTL4. The rising edge of the first 5-ms pulse is very obvious (Fig. 1). 
5. Trace the output waveform of TTL5 (or TTL7). The rising edge is less obvious but can still be seen (Fig. 2).

### Expected result

The rising edge of a pulse of any length on a TTL output should be sharp under this magnification (10 ms per grid).

_CC: @sbourdeauducq_

**Comment by hartytp** [comment]
Odd. I’ve never seen anything like that. Do you have the termination switches on?

If you have access to the hw can you stick a scope in a few places down the signal path (from lvds buffer to output) and see where this effect originated? Also worth checking nothing funny is going on with the supplies.

**Comment by gkasprow** [comment]
Don't you have AC coupling turned on in your scope?

**Comment by dhslichter** [comment]
Are you using a scope probe or connecting the signal directly in to the scope?

**Comment by hartytp** [comment]
> Don't you have AC coupling turned on in your scope?

The other thing I did wonder about was if this is related to the AC-coupled grounds. Depends whether an isolated power supply is used in the apparatus.

**Comment by dnadlinger** [comment]
A follow-up to the original forum report indicates that this also happens on DIO-BNC. (I've never seen anything like that on ours, though.)

**Comment by gkasprow** [comment]
It looks like some AC-coupling effect. Could be scope ground connected to one of four upper IOs and the signal observed on one of 4 lower outputs wi

**Comment by ghost** [comment]
Dear all,

Thank you for the replies. I've just used the oscilloscope again, using DC coupling and a 10x probe, connecting to the ground of the SMA head that is under test. However, the same shape of the rising edge is there. 

Edit: In reply to @hartytp, the termination switches are all off.

**Comment by hartytp** [comment]
> Thank you for the replies. I've just used the oscilloscope again, using DC coupling and a 10x probe, connecting to the ground of the SMA head that is under test. However, the same shape of the rising edge is there.

I don't follow you here...do you mean the tip of the probe was connected to the SMA ground (in which case, where was the probe ground connected)? Or, do you mean that the probe tip was connected to the SMA centre pin and the probe ground was connected to the SMA ground?

Can you try connecting the probe ground to the PCB ground instead of the SMA ground?

**Comment by gkasprow** [comment]
Can you connect the second channel of the scope to the 5V supply of the driver IC?

**Comment by JKQuantum** [comment]
Hi,

I'm here to report the same issue with our SMA-DIO. I also tested with/without termination switch on.

I saw a similar rising edge without termination switch on, while there was no similar rising edge is happening with the switch on. The problem with the switch is that it lowers high voltage levels from 3.6V to 2.4V, not sufficient to trigger the device we have.

Here's the picture of an oscilloscope:
![image](https://user-images.githubusercontent.com/50848069/72177262-4f8a2100-33ae-11ea-8ac6-f62b3948fecd.png)

the scope was DC-coupled, and when I add a tee and 50ohm termination, the voltage rise was sharp again but the output voltage was 1.8V, half of 3.6V.

**Comment by JKQuantum** [comment]
> Can you connect the second channel of the scope to the 5V supply of the driver IC?

I checked two test points on the board:
![image](https://user-images.githubusercontent.com/50848069/72272905-653e5700-35f7-11ea-9399-c6d49eb3ec57.png)

5.554V and 5.528V, seems reasonable.

**Comment by JKQuantum** [comment]
![image](https://user-images.githubusercontent.com/50848069/72275478-00393000-35fc-11ea-9094-9bed7ebf9f0c.png)
measured 5V (ch2) while sending pulse (ch1, 1.5ms width)

**Comment by gkasprow** [comment]
OK, this looks very intriguing. I asked my student to recreate it with exactly the same setup as yours. Hopefully, tomorrow we will be able to check what is going on.

**Comment by gkasprow** [comment]
In the past, I observed very strange behavior of the transceivers. They seemed to be sensitive to light (sic!). Their high level was dependent on whether I shined strong IR light from incandescent lamp or not. It did not work with visible LED light. It does not explain the issue you are reporting but can be related.

**Comment by gkasprow** [comment]
We recreated the issue.
![tek00010](https://user-images.githubusercontent.com/4325054/72347059-8e361900-36d7-11ea-84ea-dcc4a9333613.png)
I loaded 2 outputs with 50R and observed power supply. There is 50mV drop with small ripples
![tek00009](https://user-images.githubusercontent.com/4325054/72347091-a4dc7000-36d7-11ea-91de-70fc82d7f4c5.png)

The input signal looks fine. The output issue is the same even with 50Ohm termination.
I can also confirm that a high level depends on lighting conditions.
Set output H, turn on the strong LED light (I used my mobile phone), observe ~500mV change in the output voltage. Here is the behavior. Output terminated with 50Ohm. 
![tek00008](https://user-images.githubusercontent.com/4325054/72347149-bf164e00-36d7-11ea-9148-71eb45a85e5a.png)
The pattern was created by moving the phone above the board. This is not EMI from phone, the same effect is created by keeping the LED lamp and obscuring the light path.

**Comment by gkasprow** [comment]
The light sensitivity of the silicon IC is nothing new. I'm surprised that the black opaque package still leaks enough light that produces a measurable effect. I wouldn't connect these to effects.

**Comment by jordens** [comment]
Is this the LVDS-CMOS converter or the isolator? The isolator should be magnetic coupling not optical, right?

**Comment by JKQuantum** [comment]
With 50ohm, the high level is around 2V. Isn't it unacceptable? This is what I read from this github page:
>Outputs can supply 5V into 25Ohm, and can tolerate an indefinite short-circuit to ground.

**Comment by gkasprow** [comment]
It is just the TTL buffer chip. We have 30Ohm in series with a 25built-in resistor. It looks like we have to lower the resistor to ensure at least 2.1V in H state.

**Comment by sbourdeauducq** [comment]
The wiki suggests that the card would output 5V when connected to a 25-ohm resistor. If that's incorrect or misleading, it should be edited.

**Comment by gkasprow** [comment]
That's right. I replaced it with statement: Outputs can supply valid TTL level into 50Ohm load

**Comment by jordens** [comment]
And it's only 12.5 Ohm + 30 Ohm since we take two in parallel.

**Comment by JKQuantum** [comment]
> That's right. I replaced it with statement: Outputs can supply valid TTL level into 50Ohm load

I'm not sure. I'm certainly not electronics guy, but I was thinking ttl high should be either 3.3V or 5V. and less than 2V with 50ohm (or even with 2.1V high) doesn't satisfy any of them.

**Comment by gkasprow** [comment]
TTL does not care about the load. Input levels are the same. 50R load is used to match the impedance only, mainly for long cables. TTL input H is >2V and L is <0.8V. The same with LVTTL, that's why in TTL world you can safely connect 3.3 and 5V domains, which you cannot do in the CMOS world.
So 2V still meets the specification of H state. The surprising fact is that with 30+12Ohm : 50Ohm divider we almost get 2V at the beginning of the pulse train. Later on, we get nearly 2.5V at the end of the pulse train, without changing the supply. The same amplitude change happens when we use non-terminated output but the value is higher. 
I have one suspicion that needs to be verified. The two drivers are connected in parallel. This means that during the transition state, the skew causes cross-condiction and momentary short circuit which generates a ground bounce. However, this does not explain why after a series of pulses the circuit works properly. Maybe it heats and changes the propagation delay...

**Comment by gkasprow** [comment]
Another idea is that we use ICs from some weird series with some bugs. I will order one from another source and give it a try.

**Comment by JKQuantum** [comment]
> TTL does not care about the load. Input levels are the same. 50R load is used to match the impedance only, mainly for long cables. TTL input H is >2V and L is <0.8V. The same with LVTTL, that's why in TTL world you can safely connect 3.3 and 5V domains, which you cannot do in the CMOS world.

I think I've got your point, couldn't understand 100% though.

So my issue is, it can be out of focus though, if I were to trigger another device that needs at least ~4V high to trigger, how can I use sma-dio to do that? it can be triggered without impedance matching (>>50ohm), but the rising edge leads very long and indeterministic delay (~1ms +- 100us).

**Comment by sbourdeauducq** [comment]
You can put a terminator and use a comparator or other kind of TTL receiver that would trigger at ~2V and output 5V next to the target device. The wire length between the TTL receiver and the target device can be short so there are no issues with transmission line effects.

**Comment by gkasprow** [comment]
The DIO modules have series termination, so if your module has hi-Z input, you can use it without termination and still preserve the pulse shapes.
I ordered the transceiver ICs from other source and will test them. I have a suspicion that existing ones come from unauthorized source, even though they were bought from trusted vendor. I already met a few times fake ICs with much worse parameters than specified. The TI logo on the chips I have look suspicious.

**Comment by gkasprow** [comment]
The ICs I ordered have a different logo and markings than the ICs that cause problems. I will swap them and see if that helps.

**Comment by LTGiardino** [comment]
Hi. We've been having the exact same issue.
We found this behavior connecting the output directly into a scope (TBS2000).
Same thing using a Red Pitaya with a 10x scope probe and also with sma-sma Mini-Circuits attenuators.

Each pulse after a long period of ground state gets this same rising edge situation.
After the initial skewed edges it seems to stabilize and works correctly for every pulse afterwards.

**Comment by gkasprow** [comment]
OK, I found the issue.
It's charge build-up on the termination FET.
When I touch the FET gate with scope probe the problem disappears.
I suggest adding 10k resistors between G and S of all termination FETs.

**Comment by gkasprow** [comment]
It also explains light sensitivity - it's LED that behaves as a solar cell and opens the termination FET :) Thanks @marmeladapk for discovery of this effect

**Comment by sbourdeauducq** [comment]
Good find!

> I suggest adding 10k resistors between G and S of all termination FETs.

Has this been tested and should we rework the existing boards accordingly?

**Comment by HarryMakes** [comment]
After reworking one of the Technosystem boards by adding the 10k ohm resistor between G and S of each of the FETs, the issue has been confirmed to be fixed. To make it simple, below shown is the trace for only calling [`t4()`](https://forum.m-labs.hk/d/40-output-of-the-ttlout) on a TTL output channel.

![image](https://user-images.githubusercontent.com/66358631/103617818-d9d97680-4f69-11eb-927d-ac8adc48909f.png)

**Comment by HarryMakes** [comment]
Today, I tested a DIO_SMA v1.1 again and reproduced the problem, with slight difference in the edge shape. For simplicity, I only carried out tests to only call [`t4()`](https://forum.m-labs.hk/d/40-output-of-the-ttlout) on a TTL output channel. Below shown is the trace before doing any rework:

![image](https://user-images.githubusercontent.com/66358631/103625620-317ddf00-4f76-11eb-8d89-779bb141814c.png)

Then, we reworked the board by adding the 10k ohm resistor across each of the termination LEDs. After rework, the issue has been confirmed to be fixed. Plus, shining those LEDs with strong light (e.g. phone flashlight, laser pointer) do not change the voltage waveform. Below shown is the trace after rework:

![image](https://user-images.githubusercontent.com/66358631/103625894-8588c380-4f76-11eb-9637-6fc70d0978b9.png)

**Comment by HarryMakes** [comment]
Hi to all! Using Greg's fix ([link](https://github.com/sinara-hw/DIO_SMA/issues/4#issuecomment-733306488)), we can no longer find rising edges that last several microseconds. But recently I have observed a similar behaviour on a shorter time scale. The difference is that the rising edge last for ~200ns instead. This seem to occur only on some units of v1.2 from TechnoSystems. Attaching oscilloscope screenshots as follows:

IO0: 
![IO0](https://user-images.githubusercontent.com/66358631/118251925-c53e5980-b4da-11eb-8899-6e660d948e5e.png)

IO4: 
![IO4](https://user-images.githubusercontent.com/66358631/118251946-ca030d80-b4da-11eb-8e0a-ec003732f541.png)

Unlike the problem I found in the past, this is not negatively impacting DIO accuracy or performance, and it might not be a problem at all. I would appreciate if anyone would know an explanation. Thank you!

**Comment by gkasprow** [comment]
The TTL standard defines a valid H level as above 2.1V. So this still conforms to the standard.
The buffers we use are CMOS devices and they can be non-linear close to the rails.
How long is your cable? Is It terminated?

**Comment by HarryMakes** [comment]
@gkasprow Thank you for the feedback and info about the TTL standard. 

The cable is around 30cm long. It is an SMA coaxial cable where one end is connected to an SMA-BNC adapter for the oscilloscope, and the other end is connected directly to the SMA of the TTL channel. We set the oscilloscope in 1M ohm impedance. We didn't use any additional terminators.

**Comment by TopQuark12** [comment]
Think the issue is just impedance mismatch in test setup, see the screenshots with 1M input impedance vs 50 ohm input impedance.

![SDS2504X Plus_PNG_6](https://user-images.githubusercontent.com/32214395/122504228-6c5b6700-d02c-11eb-865e-046a0ac7c1c6.png)
![SDS2504X Plus_PNG_7](https://user-images.githubusercontent.com/32214395/122504236-6ebdc100-d02c-11eb-995f-70038219611d.png)
