### ISSUE TITLE
SMA holes on front panel are too small

### ISSUE THREAD

**Issue by HarryMakes** [sinara-hw/DIO_SMA#8]
According to the front panel design ([link here](https://github.com/sinara-hw/DIO_SMA/releases/download/v1.1/Panel.7z)), the drilled holes for fitting in the SMA connectors have a diameter of 7 mm. However, measurement on the actual front panel in production shows a diameter of 7.7 mm would be required instead. This should be fixed in order to generate a correct DXF file. Thanks.

**Comment by gkasprow** [comment]
Feel free to fix it and publish modifications. It's open-source design.

**Comment by HarryMakes** [comment]
Greg, thanks for the reply. I'm not sure how to contribute to the mechanical designs since I don't think I have the required licenses or OSes for the software (Altrium Designer?). Currently I'm using a "dirty" approach of converting the outputted DXF back to AutoCAD DWG with some online converter, editing the DWG with the [official online AutoCAD webapp](https://web.autocad.com), and converting it back to DXF again. 

Plus, I'm only suggesting 7.7 mm based on the measurement @sbourdeauducq  and I made on some manufactured panels. Certain inaccuracy might not have been accounted for. Therefore, it would be great if anyone actually involved in manufacturing at least one working front panel can contribute. I wouldn't mind taking the initiative regardless.

**Comment by gkasprow** [comment]
The panel design has 7.0mm holes. I don't know who changed the cutouts, I didn't get any feedback.
